#cloud-config
packages:
  - build-essential
  - libssl-dev
  - libffi-dev
  - python3-dev
  - python3-pip
  - libsasl2-dev
  - libldap2-dev
  - default-libmysqlclient-dev
runcmd:
  - pip install apache-superset
  - superset run -p 8088 --with-threads

